name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install JQ
      run: sudo apt-get update && apt-get install jq -y
      
    - name: Running news script
      run: export api_key="${{secrets.api_key}}" ; ./news.sh
